### ISSUE TITLE
Status of Response

### ISSUE THREAD

**Issue by Lucav17** [sarakuma/codecademy-scoop#3]
I noticed in some cases you set the status of the request before the body. Where this is fine, we typically set the status last and then return it. I also noticed in some cases you would set the status to 200 and then create an if statement that would then override it, in these cases its best just to assign it once and then return it.

[https://github.com/sarakuma/codecademy-scoop/blob/master/server.js#L123](url)

**Comment by sarakuma** [comment]
@Lucav17 Thanks for highlighting. I will take care of the above.
