### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Lucav17** [sarakuma/codecademy-scoop#4]
Overall Grade: Exceeded Standards

Pros:
- Great understanding of API and handling requests

Cons:
- None, Your code was great and I was just being nitpicky about small details

Overall:
Great job! I think you did a perfect job with requests and handling parameters! I would suggest you look into using Express.js now!

**Comment by sarakuma** [comment]
Thanks a lot for reviewing @Lucav17 
Have a good day!
